name: Simple Iris ML with CML

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-iris-model:
    runs-on: ubuntu-latest  # safer than 24.04 noble for now

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model training
        run: |
          python main.py

      - name: Comment results on PR
        if: github.event_name == 'pull_request'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create metrics.txt
